CREATE TABLE IF NOT EXISTS FTEST.AAA
(
  ID   INTEGER NOT NULL,
  NAME VARCHAR(20),
  CONSTRAINT AAA_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FTEST.BBB
(
  ID     INTEGER NOT NULL,
  AAA_ID INTEGER NOT NULL,
  NAME   VARCHAR(20),
  CONSTRAINT BBB_PK PRIMARY KEY (ID),
  CONSTRAINT BBB_AAA_FK FOREIGN KEY (AAA_ID) REFERENCES FTEST.AAA (ID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS FTEST.CCC
(
  ID     INTEGER NOT NULL,
  BBB_ID INTEGER NOT NULL,
  NAME   VARCHAR(20),
  CONSTRAINT CCC_PK PRIMARY KEY (ID),
  CONSTRAINT CCC_BBB_FK FOREIGN KEY (BBB_ID) REFERENCES FTEST.BBB (ID) ON DELETE RESTRICT,
  CONSTRAINT CCC_BBB_ID_UK UNIQUE (BBB_ID)
);